export const project = [
  {
    id: 1,
    title: "Mahasiswa Center",
    description: `Web app untuk catat harian mahasiswa ⚠️masih tahap development belum jadi sepenuhnya`,
    tools: ["Nextjs", "Tailwindcss", "Nodejs"],
    link: "https://mahasiswa-pied.vercel.app/",
  },
  {
    id: 2,
    title: "TodoApp",
    description: `Web pertama dan untuk mencatat segala sesuatu yang berkaitan dengan jadwalmu`,
    tools: ["Javascript", "HTML", "CSS"],
    link: "https://renzway.github.io/Todo/",
  },
  {
    id: 3,
    title: "Webpack Starter",
    description: `Template starter untuk membuat web memakai webpack, tinggal pakai`,
    tools: ["Javascript", "HTML", "CSS", "Webpack", "Babel"],
    link: "https://renzway.github.io/webpack-starter/",
  },
  {
    id: 4,
    title: "Clock Vanilla",
    description: `Website menampilkan jam analog berbasis vanilla`,
    tools: ["Javascript", "HTML", "CSS"],
    link: "https://renzway.github.io/clock-vanilla/",
  },
  {
    id: 5,
    title: "GoNote",
    description: "Website Todolist versi lite dari mahasiswa center",
    tools: ["React", "Webpack", "Babel", "SCSS", "Tailwindcss"],
    link: "https://gonote-center.vercel.app/",
  },
  {
    id: 6,
    title: "Web Component",
    description: "Web component bootstrap + react",
    tools: ["React", "Webpack", "Babel", "SCSS", "Bootstrap"],
    link: "https://renzway.github.io/web-components/",
  },
  {
    id: 7,
    title: "Mood Swing",
    description: "WepApp untuk mencatat mood anda hari ini",
    tools: ["Vue", "Javascript", "Tailwindcss"],
    link: "https://mood-swing-979ba.web.app/",
  },
  {
    id: 8,
    title: "Currentay",
    description: "Web current tracker",
    tools: ["Vite", "Javascript", "Bootstrap"],
    link: "https://currentay.vercel.app/",
  },
];

export const skills = [
  "React.js",
  "Next.js",
  "Tailwind CSS",
  "JavaScript",
  "Node.js",
  "Python",
  "Figma",
  "UI/UX Design",
  "Git",
  "HTML",
  "CSS",
  "Java",
  "Webpack",
  "Vite",
  "Vue",
];
