export const project = [
  {
    id: 1,
    title: "Mahasiswa Center",
    description: `Web app untuk catat harian mahasiswa`,
    tools: ["Nextjs", "Tailwindcss", "Nodejs"],
    link: "https://mahasiswa-pied.vercel.app/",
  },
  {
    id: 2,
    title: "TodoApp",
    description: `Web pertama dan untuk mencatat segala sesuatu yang berkaitan dengan jadwalmu`,
    tools: ["Javascript", "HTML", "CSS"],
    link: "https://renzway.github.io/Todo/",
  },
  {
    id: 3,
    title: "Webpack Starter",
    description: `Template starter untuk membuat web memakai webpack, tinggal pakai`,
    tools: ["Javascript", "HTML", "CSS", "Webpack", "Babel"],
    link: "https://github.com/RenzWay/webpack-starter",
  },
  {
    id: 4,
    title: "Clock Vanilla",
    description: `Website menampilkan jam analog berbasis vanilla`,
    tools: ["Javascript", "HTML", "CSS"],
    link: "https://renzway.github.io/clock-vanilla/",
  },
];

export const skills = [
  "React.js",
  "Next.js",
  "Tailwind CSS",
  "JavaScript",
  "TypeScript",
  "Node.js",
  "Express.js",
  "Python",
  "Figma",
  "UI/UX Design",
  "Git",
  "HTML",
  "CSS",
  "Java",
  "Kotlin",
  "Webpack",
  "Vite",
];
